## Lab3: Data Types and Data Structures

* Sutdent: Juan Vecino
* Group: B
* Date = 22/09/2020

### Lab 3.2 Vowels and consonants classifier

In [28]:
vowels = "a","e","i","o","u","A","E","I","O","U"

vowels_list_lower = []
consonant_list_lower = []
vowels_list_upper = []
consonant_list_upper = []

sentence = input("Write a sentence please:\n")

for character in sentence:
    if character in vowels:
        if character.islower() == True:
            vowels_list_lower.append(character)
        else:
            vowels_list_upper.append(character)
            
    else:
        if character.isupper() == True:
            consonant_list_upper.append(character)
        else: 
            consonant_list_lower.append(character)
print("Las vocales que ha utilizado son:\n-Las minúsciulas:{}\n-Las mayúsculas:{}\n\nY de las consonantes:\nLas minúsculas:{}\nLas mayúsculas:{}".format(vowels_list_lower,vowels_list_upper,consonant_list_lower,consonant_list_upper))

Write a sentence please:
Hola QUE tal GENTE?
Las vocales que ha utilizado son:
-Las minúsciulas:['o', 'a', 'a']
-Las mayúsculas:['U', 'E', 'E', 'E']

Y de las consonantes:
Las minúsculas:['l', ' ', ' ', 't', 'l', ' ', '?']
Las mayúsculas:['H', 'Q', 'G', 'N', 'T']


## Lab 3.3 Matrix multiplication

In [87]:
import numpy as np
A = np.array([[1,2,1],[3,3,4],[0,8,0]])
B = np.array([[0,0,1],[5,5,1],[2,1,1]])
C = np.array([[0,0,0],[0,0,0],[0,0,0]])

if len(A) == len(B[0]):
    for columna in range(0,len(A)):
        for fila in range(0,len(B[0])):
            for valor in range(0,len(A[0])):
                C[fila][columna] += A[fila][valor]*B[valor][columna]
else:
    print('No se pueden multiplicar estos vectores')
print(C)
if C.all() == (np.dot(A,B)).all():
    print('\nBien chaval!\n :)')

[[12 11  4]
 [23 19 10]
 [40 40  8]]

Bien chaval!
 :)


## Lab 3.4 Hands on lists methods

In [139]:
lista = ['25', 'Perro', '6.7']
print(lista[:0],lista[:],lista[:3])

lista.append(input('Que quieres añadir a la lista?\n'))
print(lista)
lista.extend(['leon', 'jirafa'])
print(lista)
#No se puede hacer si la toda la sita no es del mismo tipo.
lista.sort()
print(lista)
lista.reverse()
print(lista)
lista.insert(2,'zebra')
print(lista)
lista.remove('6.7')
print(lista)
lista.count('Perro')
print(lista)
lista.pop()
print(lista)
index = lista.index('zebra')
print(index)

[] ['25', 'Perro', '6.7'] ['25', 'Perro', '6.7']
Que quieres añadir a la lista?
gato
['25', 'Perro', '6.7', 'gato']
['25', 'Perro', '6.7', 'gato']
['25', 'Perro', '6.7', 'gato', 'leon', 'jirafa']
['25', '6.7', 'Perro', 'gato', 'jirafa', 'leon']
['leon', 'jirafa', 'gato', 'Perro', '6.7', '25']
['leon', 'jirafa', 'zebra', 'gato', 'Perro', '6.7', '25']
['leon', 'jirafa', 'zebra', 'gato', 'Perro', '25']
['leon', 'jirafa', 'zebra', 'gato', 'Perro', '25']
['leon', 'jirafa', 'zebra', 'gato', 'Perro']
2


## Lab 3.5. Saving student grades with dictionaries

In [50]:
import numpy as np

student1 = {'Name': 'Juan', 'ID':1234,'Grades':[9.3,9.7,8.5]}
student2 = {'Name': 'Esther', 'ID':4573,'Grades': [10.0,7.6,5.7]}
student3 = {'Name': 'Pedro', 'ID':1234,'Grades': [8.4,9.3,2.9]}
student_data = {}
mean_total = []

student_data = dict(student1),dict(student2),dict(student3)

for i in student_data:
    mean = np.mean(i['Grades'])
    mean_total.append(np.mean(i['Grades']))
    print('Student:',i['Name'], 'got and average:', mean)

np.mean(mean_total)

Student: Juan got and average: 9.166666666666666
Student: Esther got and average: 7.766666666666667
Student: Pedro got and average: 6.866666666666667


7.933333333333334

## Lab 3.6. Counting letters using a dictionary

In [5]:
sentence= 'Mississippi is the second longest river in the United States'
rivers = {}

for character in sentence:
    rivers[character] = rivers.get(character,0)+ 1
    #El hecho de poner .get(character , 0), nos dice que sio el valor es nulo se le añada el valor 0
    # FORMA LARGA:
    #if rivers.get(character)== None:
    #    rivers[character] = 0
    #else:
    #    rivers[character] += 1
print(rivers)

{'M': 1, 'i': 8, 's': 8, 'p': 2, ' ': 9, 't': 6, 'h': 2, 'e': 7, 'c': 1, 'o': 2, 'n': 4, 'd': 2, 'l': 1, 'g': 1, 'r': 2, 'v': 1, 'U': 1, 'S': 1, 'a': 1}
